#ifndef GLOBALSTRINGS
#define GLOBALSTRINGS
#include <QString>

//GLOBAL QSTRING VARIABLES

//SCIENTISTS
QString SCI_ORDER_BY_NAME_ASC = "SELECT * FROM Persons Order By Name ASC";
QString SCI_ORDER_BY_NAME_DESC = "SELECT * FROM Persons ORDER BY Name DESC";
QString SCI_ORDER_BY_GENDER_ASC = "SELECT * FROM Persons ORDER BY Gender ASC, Name ASC";
QString SCI_ORDER_BY_GENDER_DESC = "SELECT * FROM Persons ORDER BY Gender DESC, Name ASC";
QString SCI_ORDER_BY_BIRTH_ASC = "SELECT * FROM Persons ORDER BY Birth ASC";
QString SCI_ORDER_BY_BIRTH_DESC = "SELECT * FROM Persons ORDER BY Birth DESC";
QString SCI_ORDER_BY_DEATH_ASC = "SELECT * FROM Persons ORDER BY Death ASC";
QString SCI_ORDER_BY_DEATH_DESC = "SELECT * FROM Persons ORDER BY Death DESC";

//COMPUTERS
QString COM_ORDER_BY_NAME_ASC = "Select * FROM Computers Order By Name ASC";
QString COM_ORDER_BY_NAME_DESC = "SELECT * FROM Computers ORDER BY Name DESC";
QString COM_ORDER_BY_TYPE_ASC = "SELECT * FROM Computers ORDER BY Type ASC";
QString COM_ORDER_BY_TYPE_DESC = "SELECT * FROM Computers ORDER BY Type DESC";
QString COM_ORDER_BY_YEAR_ASC = "SELECT * FROM Copmuters ORDER BY Year ASC";
QString COM_ORDER_BY_YEAR_DESC = "SELECT * FROM Computers ORDER BY Year DESC";
QString COM_ORDER_BY_BUILT_ASC = "SELECT * FROM Computers ORDER BY Built ASC, Name ASC";
QString COM_ORDER_BY_BUILT_DESC = "SELECT * FROM Computers ORDER BY Built DESC, Name ASC";

#endif // GLOBALSTRINGS

